Added SQL script to spProduct_GetById and modified spProducts_Get
MorphineForOdin/CyberCraft pull request #19
Opened 2021-07-05 12:31 UTC by sviastyn

Added API ProductsGet and API ProductsAttributesValues

Signed-off-by: sviastyn <svyastynvasul@gmail.com>

2021-07-05 13:58 UTC, MorphineForOdin requested changes

2021-07-05 13:58 UTC, MorphineForOdin commented on src/TechMarket.API/TechMarket.API/Controllers/ProductsController.cs
> +            //todo Validation
You have added simple validation, so, you don't need this comment.

2021-07-05 13:58 UTC, MorphineForOdin commented on src/TechMarket.API/TechMarket.API/Controllers/ProductsController.cs
> +            var product = this._productsService.GetById(id);
Please, specify the explicit type and then check the result on null.

2021-07-05 13:58 UTC, MorphineForOdin commented on src/TechMarket.API/TechMarket.API/Controllers/ProductsController.cs
> +        [HttpGet("{Id:int}")]
Typo - id

2021-07-05 13:58 UTC, MorphineForOdin commented on src/TechMarket.API/TechMarket.API/Controllers/ProductsController.cs
> +            return base.Ok(product);
Please, create a response type for this.

2021-07-05 13:58 UTC, MorphineForOdin commented on src/TechMarket.API/TechMarket.API/Infrastructure/Domain/ProductAttributeValue.cs
> +        public int ValueId { get; set; }
Consider having ProductAttribute name

2021-07-05 13:58 UTC, MorphineForOdin commented on src/TechMarket.API/TechMarket.API/Infrastructure/SQL/Programmability/Stored Procedures/Products/spProduct_GetById.sql
> +CREATE PROCEDURE spProduct_GetById
spProduct**s**

2021-07-05 13:58 UTC, MorphineForOdin commented on src/TechMarket.API/TechMarket.API/Infrastructure/SQL/Programmability/Stored Procedures/Products/spProduct_GetById.sql
> +    IF @Id IS NULL OR @Id < 0
<=

2021-07-05 13:58 UTC, MorphineForOdin commented on src/TechMarket.API/TechMarket.API/Infrastructure/Services/ProductsService.cs
> +            //TODO Logic
Remove TODO comment.

2021-07-05 13:58 UTC, MorphineForOdin commented on src/TechMarket.API/TechMarket.API/Startup.cs
> +            return services
Please, revert your changes here.

2021-07-05 13:58 UTC, MorphineForOdin commented on src/TechMarket.API/TechMarket.API/TechMarket.API.csproj
> +<Project Sdk="Microsoft.NET.Sdk.Web">
Revert this change.

2021-07-05 14:36 UTC, sviastyn commented on src/TechMarket.API/TechMarket.API/Infrastructure/SQL/Programmability/Stored Procedures/Products/spProduct_GetById.sql
> +CREATE PROCEDURE spProduct_GetById
but we take only one product by this procedure

2021-07-05 14:46 UTC, sviastyn commented on src/TechMarket.API/TechMarket.API/Infrastructure/Domain/ProductAttributeValue.cs
> +        public int ValueId { get; set; }
Do you mean add "ProductAttribute " at all this properties, or only at "Name"?

2021-07-06 07:23 UTC, MorphineForOdin commented on src/TechMarket.API/TechMarket.API/Infrastructure/Domain/ProductAttributeValue.cs
> +        public int ValueId { get; set; }
Rename the file itself

2021-07-06 12:02 UTC, MorphineForOdin requested changes

2021-07-06 12:02 UTC, MorphineForOdin commented on src/TechMarket.API/TechMarket.API/Infrastructure/Domain/ProductAttribute.cs
> +        public string Value { get; set; }
By our design, each attribute could have several values.

2021-07-06 12:02 UTC, MorphineForOdin commented on src/TechMarket.API/TechMarket.API/Infrastructure/Repositories/DTOs/ProductDto.cs
> +        public IEnumerable<ProductAttributeValueDto> Properties { get; set; }
You don't need this property here.

2021-07-06 12:02 UTC, MorphineForOdin commented on src/TechMarket.API/TechMarket.API/Infrastructure/Services/ProductsService.cs
> +            return product;
Please, simplify this code by returning the repo result.

2021-07-07 12:13 UTC, closed without merging

2021-07-07 12:13 UTC, sviastyn commented
no need