Added header, footer and some header links components.
MorphineForOdin/CyberCraft pull request #25
Opened 2021-07-20 13:00 UTC by sviastyn

Signed-off-by: sviastyn <svyastynvasul@gmail.com>

2021-07-20 13:19 UTC, MorphineForOdin requested changes

2021-07-20 13:19 UTC, MorphineForOdin commented on src/TechMarket.API/TechMarket.API/Infrastructure/Services/ProductsService.cs
> +
A redundant empty line.

2021-07-20 13:19 UTC, MorphineForOdin commented on src/TechMarket.WEB/tech-market/package.json
> +    "bootstrap-icons": "^1.5.0",
Did you manage to integrate icons?

2021-07-20 13:19 UTC, MorphineForOdin commented on src/TechMarket.WEB/tech-market/src/app/app-routing.module.ts
> +    { path: 'products', loadChildren: () => import('./pages/products/products.module').then(m => m.ProductsModule) },
The empty route always should be the last in the routes array.

2021-07-20 13:19 UTC, MorphineForOdin commented on src/TechMarket.WEB/tech-market/src/app/app.component.html
> +<footer class="footer-position">
You don't need CSS classes for styling header and footer.

2021-07-20 13:19 UTC, MorphineForOdin commented on src/TechMarket.WEB/tech-market/src/app/app.module.ts
> +        AppComponent,
Remove trailing coma

2021-07-20 13:19 UTC, MorphineForOdin commented on src/TechMarket.WEB/tech-market/src/app/core/footer/footer.component.html
> +            <p>Work schedule</p>
It is an online store - so we shouldn't have a work schedule.

2021-07-20 13:19 UTC, MorphineForOdin commented on src/TechMarket.WEB/tech-market/src/app/core/header/header.component.html
> +
A redundant empty line.

2021-07-20 13:19 UTC, MorphineForOdin commented on src/TechMarket.WEB/tech-market/src/app/core/header/header.component.html
> +    <div class="header-mobile">
header-mobile?

2021-07-20 13:19 UTC, MorphineForOdin commented on src/TechMarket.WEB/tech-market/src/app/core/header/header.component.html
> +            <a href="http://localhost:4200">Tech Market</a>
Please, use relative URLs.

2021-07-20 13:19 UTC, MorphineForOdin commented on src/TechMarket.WEB/tech-market/src/app/core/header/header.component.html
> +            <button (click)="testAuth()">AuthTest</button> <!--DELETE this row-->
Delete this row.

2021-07-20 13:19 UTC, MorphineForOdin commented on src/TechMarket.WEB/tech-market/src/app/pages/landing/landing.component.html
> +        <li>{{user.email}}</li>
Please, revert this change.

2021-07-20 13:19 UTC, MorphineForOdin commented on src/TechMarket.WEB/tech-market/src/app/pages/login/login.component.html
> +                <label for="psw"></label>
password

2021-07-20 13:36 UTC, sviastyn commented on src/TechMarket.WEB/tech-market/package.json
> +    "bootstrap-icons": "^1.5.0",
I decided to download free svg icons, and move them into assets.

2021-07-22 15:11 UTC, MorphineForOdin approved these changes

2021-07-23 07:42 UTC, merged