Feature/add footer and header
MorphineForOdin/CyberCraft pull request #28
Opened 2021-08-13 15:19 UTC by Yurii-Borys

2021-08-16 10:58 UTC, BodyDuk requested changes

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.scss
> +  margin-bottom: 36px;
Please do not use pixel intervals.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.scss
> +    margin-top: 20px;
Please do not use pixel intervals.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.scss
> +  margin: 0 8px;
Please do not use pixel intervals.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.scss
> +  padding-top: 24px;
Please do not use pixel intervals.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.scss
> +  font-size: 13px;
Please do not use pixel intervals.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.scss
> +  font-size: 13px;
Please use variables for such values.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/setupTests.js
> +// learn more: https://github.com/testing-library/jest-dom
Please delete unnecessary comments.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/index.js
> +// If you want to start measuring performance in your app, pass a function
Please delete unnecessary comments.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/index.js
> +
Extra line.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.API/TechMarket.API/Controllers/ProductsController.cs
> +    //[ApiController]
Why is this code commented?

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/public/index.html
> +    -->
Please remove all unnecessary code.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/public/index.html
> +    <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
Please remove all unnecessary code.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/public/index.html
> +    -->
Please remove all unnecessary code.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/App.js
> +
Extra line.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/App.js
> +    </div>
Please format the code.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/App.scss
> +    }
Please format the code.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/api/get_categories/hooks/get_categories.js
> +
Extra line.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/api/get_categories/hooks/get_categories.js
> +            .catch((err) => console.log(err))
Please format the code.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.jsx
> +import { } from 'react-bootstrap';
Please specify which objects from the `react-bootstrap `library you are using.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.jsx
> +
Extra line.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.jsx
> +                        <div className="col-sm-6 col-md-3 item">
You can use col-6.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.jsx
> +                                        .map((categ) => <li><a href="#">{categ.name}</a></li>)}
Please provide a link for `href`.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.jsx
> +                        <div className="col-sm-6 col-md-3 item">
You can use coo-6

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.jsx
> +                        <div className="col-md-6 item text">
You can use coo-6.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.jsx
> +                            <p>Praesent sed lobortis mi. Suspendisse vel placerat ligula. Vivamus ac sem lacus. Ut vehicula rhoncus elementum. Etiam quis tristique lectus. Aliquam in arcu eget velit
Please format the code, it should not go beyond the screen.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.jsx
> +
Extra line.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.scss
> +  background-color: #282d32;
Please add constants for such values.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.scss
> +  font-size: 16px;
Please add constants for such values.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.scss
> +  font-weight: bold;
If possible, always use bootstrap classes instead of redefining your own.` mt-n/mb-n n-> (0-6)`

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.scss
> +  font-size: 14px;
Please add constants for such values.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.scss
> +  line-height: 1.6;
If possible, always use bootstrap classes instead of redefining your own.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.scss
> +  padding: 0;
If possible, always use bootstrap classes instead of redefining your own.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.scss
> +  margin-bottom: 0;
If possible, always use bootstrap classes instead of redefining your own.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.scss
> +}
If possible, always use bootstrap classes instead of redefining your own. You can achieve this effect without a media queer.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.scss
> +}
If possible, always use bootstrap classes instead of redefining your own. You can achieve this effect without a media queer.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.scss
> +}
If possible, always use bootstrap classes instead of redefining your own. You can achieve this effect without a media queer.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.scss
> +  line-height: 36px;
Please do not specify dimensions in pixels. Use relative values.(em)

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.scss
> +  color: #fff;
Please add constants for such values.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.scss
> +  margin-bottom: 0;
If possible, always use bootstrap classes instead of redefining your own.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/header/Header.jsx
> +
Extra line.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/header/Header.jsx
> +      </Navbar>
Please format the code.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/main/Main.jsx
> +
Extra line.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/main/Main.jsx
> +
Extra line.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/pages/not_found/Not_found.css
> +.page_404 {
Please use the same case for css classes throughout all files.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/pages/not_found/Not_found.css
> +    background: #fff;
Please add constants for such values.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/pages/not_found/Not_found.css
> +    font-size: 56px;
Please add constants for such values.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/pages/not_found/Not_found.css
> +    font-size: 80px;
Please add constants for such values.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/pages/not_found/Not_found.css
> +    color: #fff !important;
Please add constants for such values.
Why is this style` !important`?

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/pages/not_found/Not_found.css
> +    margin: 20px 0;
If possible, always use bootstrap classes instead of redefining your own.

2021-08-16 10:58 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/pages/not_found/Not_found.jsx
> +            <div className="text_center ">
Extra space.

2021-08-17 09:29 UTC, Yurii-Borys commented on src/TechMarket.API/TechMarket.API/Controllers/ProductsController.cs
> +    //[ApiController]
when we configure authentication on React, we will uncomment

2021-08-17 15:00 UTC, BodyDuk requested changes

2021-08-17 15:00 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.scss
> +  text-align: left;
You can specify global styles for items such as headers instead of declaring them each time.

2021-08-18 09:05 UTC, Yurii-Borys commented on src/TechMarket.WEB/tech-market/src/components/pages/not_found/Not_found.jsx
> +                <a href="/"><Button variant="outline-secondary">Go home</Button>{' '}</a>
fixed

2021-08-18 09:39 UTC, Yurii-Borys commented on src/TechMarket.WEB/tech-market/src/styles/variables.scss
> +$font_size_32px: 2em;
used converter function

2021-08-19 11:54 UTC, BodyDuk requested changes

2021-08-19 11:54 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/api/get_categories/hooks/get_categories.js
> +                    .then (respon => setData(respon.data.categories))
The indent should be one tab.

2021-08-19 11:54 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.jsx
> +                                <h3 className="mt-0 mb-2 font-weight-bold text-left">Categories</h3>
Bootstrap classes responsible for padding margining should be at the end.

2021-08-19 11:54 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.jsx
> +        <div className="footer_dark p-3 b-0">
b-0?

2021-08-19 11:54 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.jsx
> +                            <div className="d-none d-lg-block col-md-3 item">
You can use col-3.

2021-08-19 11:54 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/header/Header.jsx
> +          <Navbar.Brand href="/">Tech-market</Navbar.Brand>
Formating.

2021-08-19 11:54 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/header/Header.module.scss
> +// @media (min-width:991.98px) {
Why do you need these comments?

2021-08-19 11:54 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/header/Header.module.scss
> +    --bs-bg-opacity: 1;
Why do you need these?

2021-08-19 11:54 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/main/Main.jsx
> +            <div className='main col w-100 h-100'>
To use col you need to add a row and container.

2021-08-19 11:54 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/pages/not_found/Not_found.jsx
> +            <div className="row justify-content-center">
Why do you need these?

2021-08-19 13:19 UTC, BodyDuk requested changes

2021-08-19 13:19 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/main/Main.jsx
> +            <div className='main row w-100 h-100'>
Why do you need this?

2021-08-19 13:28 UTC, BodyDuk requested changes

2021-08-19 13:28 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/pages/not_found/Not_found.jsx
> +                <div className="col-12 text-center mt-n5 contant_box_404">
mt-n5?

2021-08-19 13:28 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/pages/not_found/Not_found.scss
> +@media (max-width: 991.98px) {
Please use bootstrap breakpoints.

2021-08-19 14:24 UTC, BodyDuk approved these changes

2021-08-20 08:06 UTC, merged