Feature/react landing page
MorphineForOdin/CyberCraft pull request #29
Opened 2021-08-16 10:50 UTC by sviastyn

Added landing page and slider component.

2021-08-16 11:12 UTC, BodyDuk requested changes

2021-08-16 11:12 UTC, BodyDuk commented on src/TechMarket.API/TechMarket.API/appsettings.Development.json
>      }
Should these changes be here?

2021-08-16 11:12 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/App.js
> +import Landing from './components/pages/landing/Landing';
Please add a line.

2021-08-16 11:12 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/Slider/Slider.css
> +    color: #fff;
Please add constants for such values.

2021-08-16 11:12 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/Slider/Slider.css
> +    height: 1em;
If possible, always use bootstrap classes instead of redefining your own.

2021-08-16 11:12 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/Slider/Slider.jsx
> +        axios.get('https://localhost:5001/api/website/sliders').then(res => {
Use the relative path.

2021-08-16 11:12 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/Slider/Slider.jsx
> +
Extra line.

2021-08-16 11:12 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/.vscode/launch.json
> +    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
Please remove all unnecessary code.

2021-08-16 11:12 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/Slider/Slider.jsx
> +        axios.get('https://localhost:5001/api/website/sliders').then(res => {
Please use the same way of working with HTTR as  @Yurii-Borys .

2021-08-16 11:35 UTC, sviastyn commented on src/TechMarket.WEB/tech-market/src/components/Slider/Slider.css
> +    height: 1em;
Bootstrap does not have appropriate classes.

2021-08-20 14:38 UTC, BodyDuk requested changes

2021-08-20 14:38 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/api/hooks/getSliderImages.jsx
> +                .catch((err) => console.log(err))
Places don't use `console.log`

2021-08-20 14:38 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/api/hooks/getSliderImages.jsx
> +export default useGetSliderImages
Please add a line at the end of the file.

2021-08-20 14:38 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/App.js
>  }
Please add a line at the end of the file.

2021-08-20 14:38 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/Slider/ImageSlider.css
> +  border-radius: 1em;
Please use one measurement unit rem or em.

2021-08-20 14:42 UTC, sviastyn commented on src/TechMarket.API/TechMarket.API/appsettings.Development.json
>      }
I will add this to gitignore at next commit

2021-08-20 14:51 UTC, BodyDuk approved these changes

2021-08-23 08:19 UTC, closed without merging