Home page.
MorphineForOdin/CyberCraft pull request #31
Opened 2021-08-23 14:48 UTC by sviastyn

2021-08-23 15:06 UTC, Yurii-Borys commented on src/TechMarket.WEB/tech-market/src/components/pages/home/Home.jsx
> +                        </ul>
If you use <li>, they must have unique key

2021-08-23 15:07 UTC, Yurii-Borys commented on src/TechMarket.WEB/tech-market/src/components/pages/home/Home.jsx
> +                        </ul>
*li

2021-08-25 07:57 UTC, BodyDuk requested changes

2021-08-25 07:57 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/Slider/ImageSlider.jsx
> +
Extra line.

2021-08-25 07:57 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/footer/Footer.scss
>  .footer_dark {
Please correct the footer or revert the change.

2021-08-25 07:57 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/pages/home/Home.jsx
> +import './Home.css';
Please prioritase imports.

2021-08-25 07:57 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/pages/home/Home.jsx
> +    let imagesData = useGetSliderImages().sliders.map(x => x.imageUrl);
Please use more meaningful names.

2021-08-25 08:35 UTC, BodyDuk requested changes

2021-08-25 08:35 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/Slider/ImageSlider.jsx
> +    };
Extra space.

2021-08-25 08:35 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/pages/home/Home.css
> +}
You can use bootstrap!

2021-08-25 08:35 UTC, BodyDuk commented on src/TechMarket.WEB/tech-market/src/components/pages/home/Home.jsx
> +                    <Col sm={12} md={4} lg={4} className='home_col'>
This breakpoint is unnecessary.

2021-08-25 08:47 UTC, BodyDuk approved these changes

2021-08-25 11:13 UTC, merged