Feature/create sql schema
MorphineForOdin/CyberCraft pull request #5
Opened 2021-06-23 14:45 UTC by sviastyn

2021-06-24 08:20 UTC, MorphineForOdin requested changes

2021-06-24 08:20 UTC, MorphineForOdin commented on src/TechMarket.API/TechMarket.API/Infrastructure/SQL/BootstrapData/Schema/011_ProductWarehouse_table.sql
> +	[ProductId] INT
Missed NOT NULL

2021-06-24 08:20 UTC, MorphineForOdin commented on src/TechMarket.API/TechMarket.API/Infrastructure/SQL/BootstrapData/Schema/011_ProductWarehouse_table.sql
> +	[Quantity] INT
NOT NULL and add a comma at the end.

2021-06-24 10:28 UTC, sviastyn commented on src/TechMarket.API/TechMarket.API/Infrastructure/SQL/BootstrapData/Schema/009_Addresses_table.sql
> +		CONSTRAINT PK_Addresses_Id PRIMARY KEY,
Fixed

2021-06-24 10:29 UTC, sviastyn commented on src/TechMarket.API/TechMarket.API/Infrastructure/SQL/BootstrapData/Schema/009_Addresses_table.sql
> +	[Address] NVARCHAR(50) NOT NULL,
Fixed

2021-06-24 10:29 UTC, sviastyn commented on src/TechMarket.API/TechMarket.API/Infrastructure/SQL/BootstrapData/Schema/009_Addresses_table.sql
> +	[ContactInfo] INT NOT NULL,
Fixed

2021-06-24 10:29 UTC, sviastyn commented on src/TechMarket.API/TechMarket.API/Infrastructure/SQL/BootstrapData/Schema/011_ProductWarehouse_table.sql
> +	[ProductId] INT
Fixed

2021-06-24 10:29 UTC, sviastyn commented on src/TechMarket.API/TechMarket.API/Infrastructure/SQL/BootstrapData/Schema/011_ProductWarehouse_table.sql
> +		CONSTRAINT FK_ProductWarehouse_ProductId FOREIGN KEY (ProductId) REFERENCES dbo.Products([Id]),
Fixed

2021-06-24 10:29 UTC, sviastyn commented on src/TechMarket.API/TechMarket.API/Infrastructure/SQL/BootstrapData/Schema/011_ProductWarehouse_table.sql
> +	[Quantity] INT
Fixed

2021-06-24 10:29 UTC, sviastyn commented on src/TechMarket.API/TechMarket.API/Infrastructure/SQL/BootstrapData/Schema/011_ProductWarehouse_table.sql
> +		CONSTRAINT FK_ProductWarehouse_WarehouseId FOREIGN KEY (WarehouseId) REFERENCES dbo.Warehouses([Id]),
Fixed

2021-06-24 15:07 UTC, MorphineForOdin requested changes

2021-06-24 15:07 UTC, MorphineForOdin commented on src/TechMarket.API/TechMarket.API/Infrastructure/SQL/BootstrapData/Schema/009_AddressesTable.sql
> +	[City] NVARCHAR(100) NOT NULL,
Please, decrease the max char limit for Name, Country, City to at least 30.

2021-06-29 12:22 UTC, MorphineForOdin requested changes

2021-06-29 12:22 UTC, MorphineForOdin commented on src/TechMarket.API/TechMarket.API/Infrastructure/SQL/BootstrapData/Schema/013_OrdersTable.sql
> +	[AddressesId] INT NOT NULL
AddressId

2021-06-29 12:22 UTC, MorphineForOdin commented on src/TechMarket.API/TechMarket.API/Infrastructure/SQL/BootstrapData/Schema/015_CartProductsTable.sql
> +	[TotalAmount] DECIMAL(10,2) NOT NULL,
Please, remove this line - because it would be duplicated for each cart product.

2021-06-29 12:22 UTC, MorphineForOdin commented on src/TechMarket.API/TechMarket.API/Infrastructure/SQL/BootstrapData/Schema/018_SP_Products_GetAll.sql
> +--============================================================================
Please, remove this file, because it is not a part of the bootstrap data scripts.

2021-06-29 15:41 UTC, MorphineForOdin requested changes

2021-06-29 15:41 UTC, MorphineForOdin commented on src/TechMarket.API/TechMarket.API/Infrastructure/SQL/Programmability/Stored Procedures/Products/018_SP_Products_GetAll.sql
> +--============================================================================
Please, remove this SP from this PR.

2021-06-29 16:10 UTC, merged